# Generated by Django 4.0.4 on 2022-06-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_datatime']},
        ),
    ]
